server:
  port: 0

spring:
  application:
    name: "eureka-client-2" # id приложения - желательно всегда в микросервисах указывать

eureka:
  client:
    #  url куда будет происходить регистрация микросервисов и других действий
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    lease-renewal-interval-in-seconds: 1