server:
  port: 0

spring:
  application:
    name: "eureka-client" # id приложения - желательно всегда в микросервисах указывать

eureka:
  client:
    #  url куда будет происходить регистрация микросервисов и других действий
    service-url:
      defaultZone: http://localhost:8201/eureka
  instance:
    lease-renewal-interval-in-seconds: 1


